import { useState } from "react";
import { Helmet } from "react-helmet-async";
import { LandingNav } from "@/components/landing/LandingNav";
import { Footer } from "@/components/landing/Footer";
import { RelatedToolsSection } from "@/components/free-tools/RelatedToolsSection";
import { getRelatedTools } from "@/lib/free-tools-data";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Sparkles, Copy, Check, Download, ArrowRight, FileCode } from "lucide-react";
import { Link } from "react-router-dom";
import { toast } from "sonner";

export default function RobotsTxtGenerator() {
  const [sitemap, setSitemap] = useState("");
  const [customRules, setCustomRules] = useState("");
  const [blockAll, setBlockAll] = useState(false);
  const [blockImages, setBlockImages] = useState(false);
  const [blockWpAdmin, setBlockWpAdmin] = useState(true);
  const [blockWpIncludes, setBlockWpIncludes] = useState(true);
  const [copied, setCopied] = useState(false);

  const generateRobotsTxt = () => {
    let content = "# robots.txt generated by AnotherSEOGuru\n";
    content += "# https://anotherseoguru.com/free-tools/robots-txt-generator\n\n";

    if (blockAll) {
      content += "User-agent: *\n";
      content += "Disallow: /\n\n";
    } else {
      content += "User-agent: *\n";
      
      if (blockWpAdmin) {
        content += "Disallow: /wp-admin/\n";
        content += "Allow: /wp-admin/admin-ajax.php\n";
      }
      
      if (blockWpIncludes) {
        content += "Disallow: /wp-includes/\n";
      }
      
      if (blockImages) {
        content += "\nUser-agent: Googlebot-Image\n";
        content += "Disallow: /\n";
      }
      
      if (customRules.trim()) {
        content += "\n# Custom rules\n";
        content += customRules.trim() + "\n";
      }
      
      content += "\n";
    }

    if (sitemap.trim()) {
      content += `Sitemap: ${sitemap.trim()}\n`;
    }

    return content;
  };

  const robotsTxt = generateRobotsTxt();

  const copyToClipboard = () => {
    navigator.clipboard.writeText(robotsTxt);
    setCopied(true);
    toast.success("Robots.txt copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const blob = new Blob([robotsTxt], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "robots.txt";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Robots.txt downloaded!");
  };

  return (
    <>
      <Helmet>
        <title>Free Robots.txt Generator - Create SEO Robots File Instantly | AnotherSEOGuru</title>
        <meta 
          name="description" 
          content="Generate a perfect robots.txt file for your website in seconds. Control search engine crawlers, block unwanted pages, and add sitemap. Free tool with instant download." 
        />
        <link rel="canonical" href="https://anotherseoguru.com/free-tools/robots-txt-generator" />
        <meta property="og:title" content="Free Robots.txt Generator - Perfect SEO Robots File" />
        <meta property="og:description" content="Create and download a custom robots.txt file for better SEO and crawler control." />
      </Helmet>

      <div className="min-h-screen bg-background">
        <LandingNav />
        
        <main className="pt-32 pb-20">
          <div className="container mx-auto px-4">
            {/* Hero */}
            <div className="max-w-4xl mx-auto text-center mb-12">
              <Badge className="mb-4 bg-primary/10 text-primary border-primary/20">
                <Sparkles className="w-3 h-3 mr-1" />
                Free Tool - No Signup Required
              </Badge>
              
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 text-foreground leading-tight">
                Free <span className="bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">Robots.txt Generator</span>
              </h1>
              
              <p className="text-lg md:text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
                Create a perfect robots.txt file for your website in seconds. Control search engine crawlers, block unwanted pages, and improve SEO.
              </p>
            </div>

            <div className="max-w-5xl mx-auto">
              <div className="grid md:grid-cols-2 gap-6 mb-8">
                {/* Configuration */}
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <FileCode className="w-5 h-5 text-primary" />
                      Configuration
                    </CardTitle>
                    <CardDescription>
                      Customize your robots.txt file
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-6">
                    <div>
                      <label className="text-sm font-medium text-foreground mb-2 block">
                        Sitemap URL
                      </label>
                      <Input
                        placeholder="https://example.com/sitemap.xml"
                        value={sitemap}
                        onChange={(e) => setSitemap(e.target.value)}
                      />
                      <span className="text-xs text-muted-foreground">Your XML sitemap location</span>
                    </div>

                    <div className="space-y-3">
                      <label className="text-sm font-medium text-foreground block">
                        Common Options
                      </label>
                      
                      <div className="flex items-center space-x-2">
                        <Checkbox 
                          id="blockAll"
                          checked={blockAll}
                          onCheckedChange={(checked) => setBlockAll(checked as boolean)}
                        />
                        <label htmlFor="blockAll" className="text-sm text-foreground cursor-pointer">
                          Block all bots (private site)
                        </label>
                      </div>

                      {!blockAll && (
                        <>
                          <div className="flex items-center space-x-2">
                            <Checkbox 
                              id="blockWpAdmin"
                              checked={blockWpAdmin}
                              onCheckedChange={(checked) => setBlockWpAdmin(checked as boolean)}
                            />
                            <label htmlFor="blockWpAdmin" className="text-sm text-foreground cursor-pointer">
                              Block /wp-admin/ (WordPress)
                            </label>
                          </div>

                          <div className="flex items-center space-x-2">
                            <Checkbox 
                              id="blockWpIncludes"
                              checked={blockWpIncludes}
                              onCheckedChange={(checked) => setBlockWpIncludes(checked as boolean)}
                            />
                            <label htmlFor="blockWpIncludes" className="text-sm text-foreground cursor-pointer">
                              Block /wp-includes/ (WordPress)
                            </label>
                          </div>

                          <div className="flex items-center space-x-2">
                            <Checkbox 
                              id="blockImages"
                              checked={blockImages}
                              onCheckedChange={(checked) => setBlockImages(checked as boolean)}
                            />
                            <label htmlFor="blockImages" className="text-sm text-foreground cursor-pointer">
                              Block image indexing
                            </label>
                          </div>
                        </>
                      )}
                    </div>

                    <div>
                      <label className="text-sm font-medium text-foreground mb-2 block">
                        Custom Rules (Optional)
                      </label>
                      <Textarea
                        placeholder="Disallow: /private/&#10;Disallow: /temp/&#10;Allow: /public/"
                        value={customRules}
                        onChange={(e) => setCustomRules(e.target.value)}
                        rows={6}
                        className="font-mono text-sm"
                      />
                      <span className="text-xs text-muted-foreground">Add custom directives</span>
                    </div>
                  </CardContent>
                </Card>

                {/* Generated File */}
                <Card>
                  <CardHeader>
                    <div className="flex items-center justify-between">
                      <CardTitle>Generated robots.txt</CardTitle>
                      <div className="flex gap-2">
                        <Button
                          onClick={copyToClipboard}
                          variant="outline"
                          size="sm"
                        >
                          {copied ? (
                            <>
                              <Check className="w-4 h-4 mr-2 text-success" />
                              Copied!
                            </>
                          ) : (
                            <>
                              <Copy className="w-4 h-4 mr-2" />
                              Copy
                            </>
                          )}
                        </Button>
                        <Button
                          onClick={downloadFile}
                          variant="outline"
                          size="sm"
                        >
                          <Download className="w-4 h-4 mr-2" />
                          Download
                        </Button>
                      </div>
                    </div>
                    <CardDescription>
                      Upload this file to your website root directory
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="bg-muted p-4 rounded-lg">
                      <pre className="text-xs text-muted-foreground whitespace-pre-wrap font-mono overflow-x-auto">
                        {robotsTxt}
                      </pre>
                    </div>
                  </CardContent>
                </Card>
              </div>

              {/* Instructions */}
              <Card className="mb-12">
                <CardHeader>
                  <CardTitle>How to Use Your Robots.txt File</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div className="flex items-start gap-3">
                      <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center flex-shrink-0">
                        <span className="text-sm font-bold text-primary">1</span>
                      </div>
                      <div>
                        <h4 className="font-semibold text-sm mb-1 text-foreground">Download or Copy</h4>
                        <p className="text-sm text-muted-foreground">
                          Click the "Download" button to save the robots.txt file, or copy the content.
                        </p>
                      </div>
                    </div>

                    <div className="flex items-start gap-3">
                      <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center flex-shrink-0">
                        <span className="text-sm font-bold text-primary">2</span>
                      </div>
                      <div>
                        <h4 className="font-semibold text-sm mb-1 text-foreground">Upload to Root Directory</h4>
                        <p className="text-sm text-muted-foreground">
                          Upload the file to your website's root directory (same folder as index.html). It should be accessible at <code className="bg-muted px-1 py-0.5 rounded">https://yoursite.com/robots.txt</code>
                        </p>
                      </div>
                    </div>

                    <div className="flex items-start gap-3">
                      <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center flex-shrink-0">
                        <span className="text-sm font-bold text-primary">3</span>
                      </div>
                      <div>
                        <h4 className="font-semibold text-sm mb-1 text-foreground">Test Your File</h4>
                        <p className="text-sm text-muted-foreground">
                          Visit <code className="bg-muted px-1 py-0.5 rounded">yoursite.com/robots.txt</code> to verify it's accessible. You can also test it in Google Search Console under the "robots.txt Tester" tool.
                        </p>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* CTA */}
              <Card className="bg-gradient-to-br from-primary/10 to-secondary/10 border-primary/20">
                <CardContent className="pt-6 text-center">
                  <h3 className="text-2xl font-bold mb-3 text-foreground">
                    Need Advanced Crawler Control?
                  </h3>
                  <p className="text-muted-foreground mb-6 max-w-xl mx-auto">
                    Get automatic robots.txt optimization, crawl budget analysis, and indexation monitoring with AnotherSEOGuru.
                  </p>
                  <Button asChild size="lg" className="gradient-primary">
                    <Link to="/auth">
                      Start Free 7-Day Trial
                      <ArrowRight className="w-5 h-5 ml-2" />
                    </Link>
                  </Button>
                </CardContent>
              </Card>
            </div>
          </div>
        </main>

        <RelatedToolsSection tools={getRelatedTools("robots-txt")} />

        <Footer />
      </div>
    </>
  );
}

